version: "3"
services:
  api:
    build: ./api
    ports:
      - 1337:80
    volumes: 
      - "./api:/var/www/html/api"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: kata-api
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8888:8080