version: "3"
services:
  api:
    build: ./api
    ports:
      - 1337:80
    volumes: 
      - "./api:/var/www/html/api"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Super
      MYSQL_DATABASE: KataManga
    volumes:
      - ../initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  web:
      build: ./api
      ports:
        - 1338:80
      volumes: 
        - "./web:/var/www/html/"
  adminer:
    image: adminer
    ports:
      - 8889:8080
